package com.hulianhujia.spellway;
/**
 * Created by FHP on 2017/7/7.
 */
public class Urls {
    public static String PUBLIC_URL="http://pintu.schlhjnetworktesturl.com/index.php?";
    public static String REGISER="m=home&c=user&a=register";
    public static String LOGIN ="m=home&c=user&a=signIn";
    public static String INIT ="m=home&c=user&a=index";
    public static String GETHOME ="m=home&c=collection&a=indexDiary";
    public static String UPDATE_COMMINUTY ="m=home&c=community&a=add";
    public static String ADD_DIARY ="m=home&c=user&a=addDiary";
    public static String GET_DIARY ="m=home&c=user&a=getDiary";
    public static String UPLOAD_IMG ="m=home&c=community&a=uploadImage";
    public static String COMMUNITY_DETAIL ="m=home&c=community&a=detail";
    public static String SEND_COMMENT ="m=home&c=judge&a=add";
    public static String DIARY_DETAIL ="m=home&c=user&a=diaryDetail";
    public static String ADD_COLLOCTION ="m=home&c=collection&a=add";
    public static String CLOLOCTION ="m=home&c=collection&a=index";
    public static String POST_LATLONG ="m=home&c=user&a=updateLocation";
    public static String GET_NEARGUIDE ="m=home&c=guide&a=nearbyGuide";
    public static String EDIT_USERINFO ="m=home&c=user&a=edit";
    public static String INVITE_GUIDE ="m=home&c=order&a=userAdd";
    public static String GET_ORDERLIST ="m=home&c=order&a=guideOrderList";
    public static String GUIDE_CONFIRMORDER ="m=home&c=order&a=guideGetOrder";
    public static String CANCEL_COLLOCTION ="m=home&c=collection&a=cancle";
    public static String GET_HOMEDIARY ="m=home&c=collection&a=index";
    public static String ORDER_DETAIL ="m=home&c=order&a=orderDetail";
    public static String START_TRAVEL ="m=home&c=order&a=startGuide";
    public static String GET_USERORDERLIST ="m=home&c=order&a=getOrders";
    public static String GUIDE_DETAIL ="m=home&c=guide&a=detail";
    public static String END_TRAVEL ="m=home&c=order&a=endGuide";
    public static String APIPAY ="m=home&c=AliPay&a=appCharge";
    public static String MESSAGELIST ="m=home&c=chat&a=chatList";
    public static String MESSAGE_DETAIL ="m=home&c=chat&a=Get";
    public static String COMMUNITY_LIST ="m=home&c=community&a=allComunity";
    public static String DIARY_LIST ="m=home&c=collection&a=getFocus";
    public static String SEND_MESSAGE ="m=home&c=chat&a=add";
    public static String GRADE_GUIDE ="m=home&c=guide&a=judgeGuide";
    public static String ADD_FOCUS ="m=home&c=focus&a=add";
    public static String GET_FOCUS ="m=home&c=focus&a=getFocus";
    public static String GUIDE_ADD_PHOTO ="m=home&c=guide&a=style";
    public static String GUIDE_GET_PHOTO ="m=home&c=guide&a=getStyle";
    public static String IS_ONDUTY ="m=home&c=guide&a=onDuty";
    public static String IS_SMS ="m=home&c=guide&a=messagePermit";
    public static String MY_COMMUNITY ="m=home&c=community&a=index";
    public static String IS_INVITE ="m=home&c=user&a=invite";
    public static String IS_USER_SMS ="m=home&c=user&a=messagePermit";
    public static String OVER_ORDER ="m=home&c=order&a=finishOrderList";
    public static String OVER_ORDER_DETAIL ="m=home&c=order&a=finishOrderDetail";
    public static String GET_CASH ="m=home&c=AliPay&a=transFer";
    public static String MONEY_LEFT ="m=home&c=guide&a=balance";
    public static String SMS_URL ="m=home&c=user&a=sendMsg";
    public static String GOT_ORDERLIST ="m=home&c=guide&a=requestOrders";
    public static String GET_CASH2 ="https://mapi.alipay.com/gateway.do?_input_charset=utf-8";
    public static String GET_RED ="m=home&c=user&a=getCoupon";
    public static String WX_PAY ="m=home&c=wxPay&a=appCharge";
    public static String HOME_FILTER_TAG ="m=home&c=user&a=DiaryTag";
    public static String HOME_FILTER_RESULT ="m=home&c=user&a=searchDiary";
    public static String GET_TALK ="m=home&c=judge&a=getJudges";
    public static String ZAN ="m=home&c=community&a=executeZan";
    public static String SERACH_GUIDE ="m=home&c=user&a=searchGuide";
    public static String SET_PINDAN_NUM ="m=home&c=guide&a=pindanpeoplenumber";
    public static String GUIDE_POINT ="m=home&c=user&a=serviceScore";
    public static String ADD_STYLE ="m=home&c=user&a=addFengcai";
    public static String IS_PINDAN ="m=home&c=guide&a=pindanPermit";
    public static String INVITE_CODE ="m=home&c=user&a=inviteCode";
    public static String CHARGE ="m=home&c=AliPay&a=make_chongzhiorder";
    public static String CHARGE_WX ="m=home&c=wxPay&a=make_chongzhiorder";
    public static String PAY_WX ="m=home&c=wxPay&a=appCharge";
    public static String PAY_BANK ="m=home&c=user&a=Balancepayment";
    public static String GETCASH ="m=home&c=user&a=tixian";
    public static String MYINVITE ="m=home&c=user&a=myinvite";
    public static String DETAIL_ACCOUNT ="m=home&c=user&a=account_log";
    public static String GOTORDER ="m=home&c=user&a=receivedorder";
    public static String REPORT ="m=home&c=user&a=fankui";
    public static String GRADE_APP ="m=home&c=user&a=appscore";
    public static String REFUSE_ORDER ="m=home&c=order&a=guideRefuse";
    public static String RESET_PWD ="m=home&c=user&a=editpassword";
    public static String CANCEL_COLLECT ="m=home&c=collection&a=cancle";
    public static String DELET_ORDER ="m=home&c=order&a=deleteorder";
    public static String GET_HXPWD ="m=home&c=user&a=gethuanxin_password";
    public static String SHARE_COM ="m=home&c=community&a=share_community";
    public static String DELETE_NEWS ="m=home&c=community&a=del_community";
}
